### ISSUE TITLE
Expectations on backtracking time/performance?

### ISSUE THREAD

**Issue by justonia** [BorisTheBrave/DeBroglie#1]
I've implemented both the adjacent and overlapping models into Unity's Tilemap system and I've recreated this example:

![image](https://user-images.githubusercontent.com/89791/47447781-9aa11f80-d77b-11e8-8ab6-ed72de55cf8b.png)

Every five or so runs of the overlapping model generation process I get stuck in a seemingly endless generation process. When I check the backtrack count it's in the millions, and I end up just canceling the operation as it never seems to complete (I've waited 10's of minutes on a high powered system).

I know the backtracking algorithm in the worst case will search the entire problem space, but should I expect such behavior in this example? My tilemap output size is only 40x40.

**Comment by BorisTheBrave** [comment]
Looks nice. It could be the problem with backtracking is memory consumption - can you check what your memory usage is like while the operation is running? For me, even medium sized tests quickly use up all my system memory and then stall on paging - they typically don't get huge backtrack counts though, so it'd be interesting to see what you observe.

Can you also clarify what settings you've used. Do you have symmetry set? Are you using any constraints.

**Comment by justonia** [comment]
Memory isn't an issue. The size of the wavePropagator.prevWaves.Count stays consistently under 500. I have no constraints set, and no symmetry.

My gut says there is a bug lurking in there because in a current run I am seeing that count oscillate between 330 and 290, never growing and never shrinking/expanding outside of those bounds. The code is complex, so I haven't been able to find anything myself yet.

**Comment by justonia** [comment]
Oh for no symmetry of any kind, sanity check me (I was confused by the integer symmetry notation):

```var model = new OverlappingModel(tiles.ToTiles(), n, 1, false)```

**Comment by BorisTheBrave** [comment]
Yes, that's symmetry off. I think you'll have better luck with symmetry = 8 (i.e. fully symmetric). That's because the input sample is really very small - there's not much variation in it. In particular there are not examples of all the possible corners, which means some configurations are impossible to complete. Adding 7 extra rotated / reflected copies gives the WFC algorithm a lot more to work with when it comes to completing the last few tiles.

**Comment by justonia** [comment]
Enabling those symmetries definitely made the solver find solutions more reliably. 

It does balloon backtracking memory to the point where it is capable of crashing Unity though :). Not a big deal right now, I've implemented a brute force alternative of just retrying the generation when a Contradiction is found. Won't scale well to a lot of constraints, but I'll play with it. I may even go super brute-force at that point and spin up a ton of threads to churn away until something is found.

If I used a TileRotationBuilder with a complete tileset, would that use less memory than the automatic symmetry builder under the hood?

**Comment by BorisTheBrave** [comment]
No, they'll use the same memory.

There's no workaround atm except turning off backtracking and retrying generation, as you've already figured out. Atm backtracking is only appriorate for small examples. 

Please let me know if backtracking is particularly important to your use cases, and I can prioritize improving it in future.

**Comment by justonia** [comment]
I'm not going to worry about backtracking at all for quite a while, brute force can get you quite a ways if you are willing to throw enough CPU at it. 

I had been wondering if there is a probabilistic approach to it where the deeper you go into a search tree, the more likely you are to abort and recurse much higher back "up" to try a different path. I am probably misunderstanding the complexities of the wave propagation algorithm in this idea though. :)

Alternatively, if the memory usage could somehow be compressed by an order of magnitude, you might be able to multithread the search process in some way too.

Anyways, thank you for making this! I saw when you posted it to Reddit, and it's been fun finally digging into this algorithm with a well designed and documented implementation.

**Comment by justonia** [comment]
Oh and one other enhancement I had considered that has value in games specifically, would be an option to use fixed-point math instead of floats. Being able to share seeds for content generation is a fun feature. I'd look into using this if I tried it: https://github.com/asik/FixedMath.Net

**Comment by BorisTheBrave** [comment]
I have a fairly clear idea how to improve the backtracking, it's just not implemented. Your suggestions are good, but until I make some enhancements on memory consumption it's always going to get bogged down.

There's no need for fixed point maths. The library is already fully deterministic. [TilePropagator ](https://boristhebrave.github.io/DeBroglie/api/DeBroglie.TilePropagator.html#DeBroglie_TilePropagator__ctor_DeBroglie_Models_TileModel_DeBroglie_Topo_Topology_System_Boolean_DeBroglie_Constraints_ITileConstraint___System_Random_) takes a `Random` argument. If you pass in one initialized with a fixed seed, you'll always get the same results.

**Comment by justonia** [comment]
Oh silly me, for some reason I had thought the probabilities was using floats. Ignore me! :)

**Comment by BorisTheBrave** [comment]
It does use floats. But floats only introduce non-determinism when you do maths operations that give different answers on different machines. This library should be free of that (though admittedly I have not tested).

**Comment by justonia** [comment]
Pretty much any float operation as simple as an add or multiply will break determinism. Compiler optimizations, different builds, different platforms, different CPUs (even within the same family), out of order execution, etc etc all make it pretty much a guarantee it won't work. I've been bit by this hard in the past on one project.

**Comment by BorisTheBrave** [comment]
While I agree that is possible, I don't think it is a concern. The use of floats here is not chaotic - small errors do not accumulate to big errors. I think I will leave addressing that until I've got reports of it actually being a problem.

**Comment by justonia** [comment]
Yea no biggy, doesn't get in the way of using it by any means. Did you have some ideas already on reducing memory usage? That might be something I could dig into at some point in the future. For instance using a BitArray instead of arrays of bools?

**Comment by BorisTheBrave** [comment]
I'd be happy to accept a patch.
Unfortunately, using a bitset won't help much as the `Wave` object also stores `EntropyValues` which is much larger than a bool. My plans, in order from easiest to hardest:

1) Add an option to truncate the backtrack history to a fixed depth.
2) Make `WaveArchive` which is a bitset version of wave with no entropy information. Reconstruct `Wave` from `WaveArchive` as necessary.
3) Make `Wave` a persistent data structure, so that successive changes to `Wave` can share most of their reprsentation.

**Comment by BorisTheBrave** [comment]
Wait, actually you are right, simply changing to a bitset would probably make a lot of difference. I may have a shot at that soon as it is pretty low hanging.

**Comment by BorisTheBrave** [comment]
I'm closing as I think I've answered your questions, and you've opened issues  #2 and #3 for the features discussed.
