### ISSUE TITLE
Plans for Generated Tiles feature?

### ISSUE THREAD

**Issue by minism** [BorisTheBrave/DeBroglie#10]
Hey, firstly thanks for your hard work on this library, I've been having a blast with it recently on unity.

My setup right now is a pipeline that operates on [TileBase](https://docs.unity3d.com/ScriptReference/Tilemaps.TileBase.html) as sample value, for both input and output (i.e. a reference unity tilemap is used to generated an output unity tilemap).

I'd love to take advantage of the generated tiles feature for symmetry, however when doing so I get

```
InvalidCastException: Specified cast is not valid.
(wrapper castclass) System.Object.__castclass_with_cache(object,intptr,intptr)
DeBroglie.TilePropagator.ToValueArray[T] (T undecided, T contradiction) (at Assets/Plugins/DeBroglie/TilePropagator.cs:493)
```

The cast happens here:

https://github.com/BorisTheBrave/DeBroglie/blob/29a127309182f69b42a7735dc262b1010ee13455/DeBroglie/TilePropagator.cs#L491

Honestly, I didn't expect this to really work in the first place though.  It seems there would need to be some API by which you tell DeBroglie *how* to generate tiles which are rotations of other tiles.  For example, bitmap data can be rotated, but for Unity Tilemap tiles, you just want to store some metadata about how the tile is rendered in the tilemap (Specifically, tile.transform).

I was wondering if you had thoughts on how this should be handled?  I would be happy to help contribute.

**Comment by minism** [comment]
Nevermind!  I see it is because the Propagator no longer returns a homogeneous TopoArray, it can return T or RotatedTile.

I was able to solve it with something like the following:

```
  private ITopoArray<TileBase> TransformRotatedTiles(ITopoArray<object> source) {
    return TopoArray.Create((point) => {
      var obj = source.Get(point.X, point.Y, point.Z);
      if (obj is TileBase) {
        return obj as TileBase;
      } else if (obj is RotatedTile) {
        // TODO process rotation
      }
      return null;
    }, source.Topology);
  }
```

**Comment by BorisTheBrave** [comment]
Yeah, you basically got that figured out. The difference between T and RotatedTile is annoying, but that's how the API worked out.

Two things to note:

1. You may find it easier to use .Map rather than .Create.

2. Using RotatedTile is entirely optional. You can configure TileRotationBuilder in several ways, which means you can get it to understand Unity’s notion of rotation.i did something similar in my own unity projects.
