### ISSUE TITLE
Does rotation affect path Constraints?

### ISSUE THREAD

**Issue by liu0fanyi** [BorisTheBrave/DeBroglie#14]
I use path with index 2, and get this
![image](https://user-images.githubusercontent.com/3987452/93843502-9ca7ec00-fccc-11ea-9575-cafee80eeb37.png)

And I config rotation with:
```
{
    "rotationTreatment": "generated",
    "rotationalSymmetry": 6,
    "reflectionalSymmetry": true,
}
```

and I will get this:
![image](https://user-images.githubusercontent.com/3987452/93843787-ad0c9680-fccd-11ea-9586-e778f3718098.png)

I can't understand what happened here...
I know there is no need to rotate here. But I have another sample need rotate, and generated.
So I want use a simiple sample to see what's wrong.

Any help? Thanks a lot.

**Comment by BorisTheBrave** [comment]
Yes, definitely seems like an error. I've reviewed the code and it does look ok, it should be automatically dealing with the rotated copies.

Could you perhaps attach the files you are working with so I can test them directly?

**Comment by BorisTheBrave** [comment]
Actually, are you using Path or EdgedPath? Only the latter looks like it handles generated tiles for you.

**Comment by BorisTheBrave** [comment]
I've pushed a fix that I think should help things. Please checkout master and let me know.
