### ISSUE TITLE
Exception while running propagator: Deque is empty

### ISSUE THREAD

**Issue by svwilke** [BorisTheBrave/DeBroglie#17]
Hey BorisTheBrave,

I've been running into the above mentioned exception with a backtracking setup. I'm using the C# library and not the console application, if that makes any difference at all.
The backtracking depth is set to infinite (though this also happens with any finite depth set), and I'm using multiple constraints.
However the map is definitely generatable, as I only get this exception sometimes, and other times an output is produced.

Do you happen to know what's causing this?

This is the stacktrace:
```cs
  at DeBroglie.Wfc.Deque`1[T].Pop () [0x00010] in <4ff1c6a8afd84a669432e1334eba5546>:0 
  at DeBroglie.Wfc.WavePropagator.Step () [0x0013c] in <4ff1c6a8afd84a669432e1334eba5546>:0 
  at DeBroglie.Wfc.WavePropagator.Run () [0x00000] in <4ff1c6a8afd84a669432e1334eba5546>:0 
  at DeBroglie.TilePropagator.Run () [0x00000] in <4ff1c6a8afd84a669432e1334eba5546>:0
```

Cheers

**Comment by BorisTheBrave** [comment]
AFAIK that should only occur if generation is impossible. What constraints
/ settings are you using.

**Comment by svwilke** [comment]
Thanks for the quick reply. Turns out after some investigation that this was indeed caused by an impossible generation state. It turns out that I had a random factor in one of my custom constraints, which caused it to sometimes place invalid tiles.

Thanks again for the quick support. I suggest throwing a more specific/verbose exception when this case occurs, so future users will not end up confused like me.
