### ISSUE TITLE
Is there a way to see what triggers a contradiction?

### ISSUE THREAD

**Issue by Sajdkick** [BorisTheBrave/DeBroglie#19]
I'm trying to use an overlap model to generate a map, but I keep getting contradictions. When i inspect the propagator I can see that it doesn't backtrack at all, so i assume that something is wrong with my map and constraints which is fair. But it's really tough to debug when all the information i get is "Contradiction". Is there a way to get more information?

Thanks :)

**Comment by BorisTheBrave** [comment]
Hi Sajdkick, you can get more information by inspecting the propagator. The .ToArraySets() method will output the current possible tiles, typically there will be at least one location which has zero possible tiles, indicating where the exception is. You can also inspect nearby locations to see what tiles contributed to the problem.
