### ISSUE TITLE
No idea if the algorithm is stuck, have crashed, or just takes a long time

### ISSUE THREAD

**Issue by Sajdkick** [BorisTheBrave/DeBroglie#20]
Would love to be able to toggle some kind of console output when running so that i can get an insight into how the algorithm is progressing, just so i know that it's actually doing something!

**Comment by BorisTheBrave** [comment]
I believe the console program is already coded to output the percentage progress once a minute or every 100 steps, whichever is longer. Is that not working for you?

**Comment by Sajdkick** [comment]
I'm integrating it with my own code so im not using the prebuilt console application, is there a way to implement that myself?

**Comment by BorisTheBrave** [comment]
Yes. Do not call Run, instead call Step inside of a while loop, and check
the status each iteration. You can add any other checks or logging to the
loop.
