### ISSUE TITLE
A possibility of probability?

### ISSUE THREAD

**Issue by berkut0** [BorisTheBrave/DeBroglie#23]
Is it possible to control explicitly the probabilities of the appearance of the tiles?
I'm sorry, I just started working with the library and just beginning to understand how it works, I may have missed the obvious.

For example I want to tie the probability to a cell value - for example, brightness or something else. I want to tie the probability of the appearance of the tiles to the value of the grid.

**Comment by BorisTheBrave** [comment]
AdjacentModel.SetFrequency or OverlappedModel.MultiplyFrequency let you set the frequencies globally.

If you want to set it per-cell, you can use `TilePickerType.ArrayPriority`, and fill in `WeightSetByIndex` and `WeightSets` appropriately.

Please join my discord (https://discord.gg/FguMExwb) for further support.
